### PR TITLE
Add support for shared library build using -DBUILD_SHARED_LIBS=ON

### PR DESCRIPTION
**Pull request by jimpark**
I've also added the ability to install the generated output files.

It has been tested on Windows using Visual Studio, macOS, and Ubuntu Bionic.

### CODE REVIEW

**Comment by dacap** [comment]
Hi @jimpark, I'm not 100% sure about this one, I have to think more about it.

To create DLLs the best case would be a C wrapper for the C++ API, to avoid having a dependency with the exact same C++ runtime. A problem that I had some time ago with [vaca](https://github.com/dacap/vaca), is that the library must be compiled with the exact same flags, because in other case, any object created from the library side will not be compatible with the client side (cannot be deleted in the client side). A possible solution about this would be using `std::shared_ptr`s.

Also I'm not sure if we need to depend on `CMakePackageConfigHelpers` and `GNUInstallDirs`. I would prefer a simple way to discover the `clip` library by other projects (using `find_library` instead of the need of using installed `.cmake` files). Anyway I have never used those packages so I'm not sure how a client should use the installed files.

At the moment the library must be used as a static library. In the future I'll try to reproduce the same bugs I had with *vaca* in MSVC and check how we can avoid them.

**Comment by jimpark** [comment]
When we consume C++ DLLs, we know the limitations. While a C ABI is stable, it lacks the expressiveness of the C++ interface. Since this change doesn't force a C++ DLL to be made but simply makes it _possible_, I think it's a safe and useful feature. I build my chain of libraries for my products with the same compiler and the same settings. It's part of the toolchain. Just building a C++ library and shipping it has very limited usefulness because of the problems you describe. But having it part of your build is very very useful. I'd ask you to reconsider.

As for CMakePackageConfigHelpers, it makes CMake projects find each other very easily. find_library() will use its heuristics to try to find packages and that will work as usual. However, if it finds the .cmake files, it makes it very definite. Not only that, it allows for inheriting build properties which alleviates in large part the C++ build setting problems you were talking about. So it only helps and does not in any way hinder what find_library normally does.

**Comment by API-Beast** [comment]
clip is designated neither as static nor shared library, as such it should be enough to simply set the cmake variable "[BUILD_SHARED_LIBS](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html)" to ON in your configuration. No need to make any changes in the CMakeLists.txt.

**Comment by API-Beast** [comment]
Ah, I found this CMake property that should make this pull request unnecessary:
[WINDOWS_EXPORT_ALL_SYMBOLS](https://cmake.org/cmake/help/v3.4/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html)

**Pull request closed without merging**
